# Generated by Django 5.1.3 on 2024-11-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subvariants',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-CreatedDate', 'ProductID')},
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='products',
            name='CreatedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='products',
            table='products_product',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.products')),
            ],
        ),
        migrations.CreateModel(
            name='SubVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariants', to='api.variant')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='SubVariants',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
